name: test cache
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: clone rekor
        run: |
          git clone https://github.com/sigstore/rekor
      - name: docker compose up
        run: |
          cd rekor
          docker compose up -d --wait
