name: test setup-sigstore-env
on:
  workflow_dispatch:
  push:
    paths:
      - 'actions/setup-sigstore-env/**'
  pull_request:
    paths:
      - 'actions/setup-sigstore-env/**'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and cache cosign
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          file: ./actions/setup-sigstore-env/Dockerfile.cosign
          tags: cosign
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and cache fakeoidc
        uses: docker/build-push-action@v3
        with:
          context: ./actions/setup-sigstore-env/fakeoidc
          load: true
          tags: fakeoidc
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: fetch fulcio repo
        run: |
          for repo in fulcio rekor rekor-tiles timestamp-authority ; do
            git clone https://github.com/sigstore/${repo}
          done
      - name: cache fulcio docker compose images
        uses: docker/bake-action@master
        with:
          source: .
          workdir: ./fulcio
          push: false
          load: true
          files: |-
            docker-compose.yml
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - name: cache rekor docker compose images
        uses: docker/bake-action@master
        with:
          source: .
          workdir: ./rekor
          push: false
          load: true
          files: |-
            docker-compose.yml
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - name: cache rekor-tiles docker compose images
        uses: docker/bake-action@master
        with:
          source: .
          workdir: ./rekor-tiles
          push: false
          load: true
          files: |-
            compose.yml
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - name: cache timestamp-authority docker compose images
        uses: docker/bake-action@master
        with:
          source: .
          workdir: ./timestamp-authority
          push: false
          load: true
          files: |-
            docker-compose.yml
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - id: setup-sigstore-env
        uses: ./actions/setup-sigstore-env
      - uses: sigstore/cosign-installer@fb28c2b6339dcd94da6e4cbcbc5e888961f6f8c3 # v3.9.0
        with:
          cosign-release: main
      - name: make test data
        run: echo "gundam" > data.txt
      - name: test-sign
        env:
          SIGSTORE_CT_LOG_PUBLIC_KEY_FILE: ${{ steps.setup-sigstore-env.outputs.ct-log-key }}
        run: |
          echo token:
          curl -f ${{ steps.setup-sigstore-env.outputs.oidc-url }}/token
          cosign sign-blob \
            -y \
            --bundle=bundle.json \
            --new-bundle-format=true \
            --rekor-url http://localhost:3000 \
            --fulcio-url http://localhost:5555 \
            --oidc-issuer ${{ steps.setup-sigstore-env.outputs.oidc-url }} \
            --identity-token ${{ steps.setup-sigstore-env.outputs.oidc-token }} \
            data.txt
      - name: test-verify-with-trusted-root
        run: |
          cosign verify-blob \
            --trusted-root ${{ steps.setup-sigstore-env.outputs.trusted-root }} \
            --bundle bundle.json \
            --new-bundle-format=true \
            --certificate-identity foo@bar.com \
            --certificate-oidc-issuer ${{ steps.setup-sigstore-env.outputs.oidc-url }} \
            data.txt
