name: test cache
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: clone rekor
        run: |
          git clone https://github.com/sigstore/rekor
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: cache rekor docker compose images
        uses: docker/bake-action@master
        with:
          source: .
          workdir: ./rekor
          push: false
          load: true
          files: |-
            docker-compose.yml
          set: |
            trillian-log-server.cache-from=type=gha
            trillian-log-server.cache-to=type=gha,mode=max
            trillian-log-signer.cache-from=type=gha
            trillian-log-signer.cache-to=type=gha,mode=max
            rekor-server.cache-from=type=gha
            rekor-server.cache-to=type=gha,mode=max
      - uses: ./actions/test-cache
